### ISSUE TITLE
New TOSA logo not showing up on Tinyman

### ISSUE THREAD

**Issue by tosainucoin** [tinymanorg/asa-list#143]
The new logo was merged with the main branch 21 days ago but for some reason is not updating on Tinyman.

**Comment by ertekinno** [comment]
"Tinyman app will read the ASA icons directly from the S3 bucket. From now on, all ASA icons will be automatically updated on the Tinyman website at once."

Thanks for your patience. The new logo should be updated on the Tinyman app by now.
