### ISSUE TITLE
CCT - 657291910

### ISSUE THREAD

**Issue by CCTJoy** [tinymanorg/asa-list#507]
![icon](https://user-images.githubusercontent.com/107363536/173244573-1713c746-8af7-4728-a57e-a70cf2eef5f5.png)
![icon](https://user-images.githubusercontent.com/107363536/173244575-2482c73d-0635-45f5-baf7-d1151ed0d51a.svg)

**Comment by ertekinno** [comment]
Hello, thanks for sending icons. Unfortunately, this is not suitable to the repository. You should create a pull request, not issue.

- First, you should create a folder. There should be a folder named with `unit_name-asset_id`, e.g. "USDC-31566704" without adding any space. And icon files should be in this folder.
- Icon names should be `icon.png` and `icon.svg`
- Icon.svg and icon.png should show the same icon. Right now, the SVG file is just a image-traced version of PNG file. Colors are not consistent.

Please update your commit according to this feedback. You can view all the requirements from [README.md](https://github.com/tinymanorg/asa-list/tree/main#readme) before creating a pull request.

**Comment by CCTJoy** [comment]
Hi Tinyman team,
Thank you! I have re-submitted a pull request #523 six days ago.

Would you be able to kindly advise when this can be completed?

Many thanks,
Joy

Joy Guo
COO
Carbon Credit Token
